#!/bin/sh
set -eu
IMAGE_PREFIX="${IMAGE_PREFIX:-ckware/rudy}"
distros="${1:-.*}"
build_context="$(dirname "${0}")/image"
find "${build_context}" -maxdepth 1 -regex "${build_context}/Dockerfile\.${distros}" -printf '%f\n' \
| while read file; do
  distro="${file##Dockerfile.}"
  find  "${build_context}" -mindepth 1 -maxdepth 1 -type d ! -name common -printf '%f\n' \
  | while read service; do
    docker build \
    -t "${IMAGE_PREFIX}-${service}:${distro}" \
    -f "${build_context}/Dockerfile.${distro}" \
    --build-arg "SERVICE=${service}" \
    "${build_context}"
  done
done
