FROM debian:bullseye-slim
RUN  apt-get update && apt-get install -y usbip && apt-get clean
ARG  SERVICE
ENV  USBIP_HOME="/opt/usbip-${SERVICE}"
COPY usbip-common.sh "${SERVICE}/init" "${USBIP_HOME}/"
CMD  exec "${USBIP_HOME}/init"
