FROM debian:bookworm-slim
RUN  apt-get update && apt-get install -y usbip netcat-openbsd mosquitto-clients && apt-get clean
ARG  SERVICE
ENV  RUDY_HOME="/opt/rudy-${SERVICE}"
ENV  PATH="${PATH}:${RUDY_HOME}"
COPY common/* "${SERVICE}/run" "${RUDY_HOME}/"
CMD  exec "${RUDY_HOME}/run"
