FROM debian:buster-slim
RUN  apt-get update && apt-get install -y usbip netcat mosquitto-clients && apt-get clean
ARG  SERVICE
ENV  RUDY_HOME="/opt/rudy-${SERVICE}"
ENV  PATH="${PATH}:${RUDY_HOME}"
COPY common/* "${SERVICE}/run" "${RUDY_HOME}/"
# bash is preferred over sh as workaround for
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779416
# affected package is dash:0.5.10.2-5, fixed in 0.5.11
CMD  exec bash "${RUDY_HOME}/run"
